# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node

pipelines:
 branches:
    dev:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            #- npm run unit
            - apiBaseUrl="https://ff-app-dev.appspot.com" npm run build
            - npm install -g firebase-tools --unsafe
            - firebase deploy --token ${FIREBASE_TOKEN_DEV} --project default
    prod:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            #- npm run unit
            - apiBaseUrl="https://ff-app-prod.appspot.com" npm run build
            - npm install -g firebase-tools --unsafe
            - firebase deploy --token ${FIREBASE_TOKEN_PROD} -P prod
definitions:
  services:
    selenium:
      image: selenium
